spring:
  h2:
    console:
      enabled: true
      path: /h2-console # H2???? console ?? ??
  datasource:
    url: jdbc:h2:mem:jeulog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true # SQL ?? ?? ???
        use_sql_comments: true # SQL ??? /* */ JPQL ?? ??

logging:
  level:
    org.hibernate:SQL: debug # SQL ?? ?? ??
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # ???? ???? ?? ??
