spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:jeulog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true # SQL 보기 좋게 포맷팅
        use_sql_comments: true # SQL 내부에 /* */ JPQL 주석 추가
  data:
    web:
      pageable:
        one-indexed-parameters: true # 페이지 1부터 시작
        default-page-size: 5

logging:
  level:
    org.hibernate:SQL: debug # SQL 쿼리 로그 출력
    org.hibernate.orm.jdbc.bind: trace # 스프링 부트 3.XX 이상 SQL 파라미터 바인딩 정보 표시
