spring:
  h2:
    console:
      enabled: true
      path: /h2-console # H2???? console ?? ??
  datasource:
    url: jdbc:h2:mem:jeulog
    username: sa
    password:
    driver-class-name: org.h2.Driver

